public class class_main {
	public static void main(String[] args) {
		Kotak kotakHitam = new Kotak();
		kotakHitam.setPanjang(20);
		kotakHitam.setLebar(10);
		kotakHitam.hitungLuas();
		kotakHitam.hitungKeliling();
			System.out.println("Panjang : " + kotakHitam.getPanjang());
			System.out.println("Lebar : " + kotakHitam.getLebar());
			System.out.println("LuasKotak : " + kotakHitam.getLuas());
			System.out.println("KelilingKotak " + kotakHitam.getKeliling());
			System.out.println("___________________________________________");
			//Hasil Mahasiswa
			Mahasiswa mhs1 = new Mahasiswa();
			mhs1.setNama("Ismail Umar");
			mhs1.setNim("D0217308");
			mhs1.setAlamat("Pambusuang");
			mhs1.setGolonganDarah("A");
			mhs1.setStatus("Mahasiswa");
			mhs1.setTinggiBadan(170);
			mhs1.setBeratBadan(49);
			System.out.println("Nama : " + mhs1.getNama());
			System.out.println("Nim : " + mhs1.getNim());
			System.out.println("Alamat : " + mhs1.getAlamat());
			System.out.println("GolonganDarah : " + mhs1.getGolonganDarah());
			System.out.println("Status : " + mhs1.getStatus());
			System.out.println("TinggiBadan : " + mhs1.getTinggiBadan());
			System.out.println("BeratBadan : " + mhs1.getBaratBadan());
			System.out.println("---------------------------------------------");
			System.out.println("------Object Kelas node------");
			//membuat object darikelas node
			node node = new node();
			//method setter node
			node.label = "COCA-COLA";
			node.Value = 1;
			//method getter node
			System.out.println("Nama Label : " + node.getlabel());
			System.out.println("jumlah label : " + node.getValue());
			//membuat object darikelas stack
			stack stack = new stack();
			System.out.println("------Object Kelas stack------");
			stack.value[0] = "Ismail Umar";
			stack.value[1] = "KAU";
			stack.value[2] = "PUTUSKAN";
			stack.value[3] = "AKU";
			stack.value[4] = "DISAAT";
			stack.value[5] = "DIRIKU";
			stack.value[6] = "MERANA";
			stack.value[7] = "AKAN";
			stack.value[8] = "TUGAS";
			stack.value[9] = "KULIAHKU";
			stack.value[10] = "Buku";
			stack.value[11] = "Buku";
			stack.value[12] = "Buku";
			stack.value[13] = "Buku";
			stack.value[14] = "Buku";
			stack.value[15] = "Buku";
			stack.value[16] = "Buku";
			stack.value[17] = "Buku";
			stack.value[18] = "Buku";
			stack.value[19] = "Buku";
			stack.value[20] = "Buku";
			stack.value[21] = "Buku";
			stack.value[22] = "Buku";
			stack.value[23] = "Buku";
			stack.value[24] = "Buku";
			stack.value[25] = "Buku";
			stack.value[26] = "Buku";
			stack.value[27] = "Buku";
			stack.value[28] = "Buku";
			stack.value[29] = "Buku";
			stack.value[30] = "Buku";
			stack.value[31] = "Buku";
			stack.value[32] = "Buku";
			stack.value[33] = "Buku";
			stack.value[34] = "Buku";
			stack.value[35] = "Buku";
			stack.value[36] = "Buku";
			stack.value[37] = "Buku";
			stack.value[38] = "Buku";
			stack.value[39] = "Buku";
			stack.value[40] = "Buku";
			stack.value[41] = "Buku";
			stack.value[42] = "Buku";
			stack.value[43] = "Buku";
			stack.value[44] = "Buku";
			stack.value[45] = "Buku";
			stack.value[46] = "Buku";
			stack.value[47] = "Buku";
			stack.value[48] = "Buku";
			stack.value[49] = "Buku";
			stack.value[50] = "Buku";
			stack.value[51] = "Buku";
			stack.value[52] = "Buku";
			stack.value[53] = "Buku";
			stack.value[54] = "Buku";
			stack.value[55] = "Buku";
			stack.value[56] = "Buku";
			stack.value[57] = "Buku";
			stack.value[58] = "Buku";
			stack.value[59] = "Buku";
			stack.value[60] = "Buku";
			stack.value[61] = "Buku";
			stack.value[62] = "Buku";
			stack.value[63] = "Buku";
			stack.value[64] = "Buku";
			stack.value[65] = "Buku";
			stack.value[66] = "Buku";
			stack.value[67] = "Buku";
			stack.value[68] = "Buku";
			stack.value[69] = "Buku";
			stack.value[70] = "Buku";
			stack.value[71] = "Buku";
			stack.value[72] = "Buku";
			stack.value[73] = "Buku";
			stack.value[74] = "Buku";
			stack.value[75] = "Buku";
			stack.value[76] = "Buku";
			stack.value[77] = "Buku";
			stack.value[78] = "Buku";
			stack.value[79] = "Buku";
			stack.value[80] = "Buku";
			stack.value[81] = "Buku";
			stack.value[82] = "Buku";
			stack.value[83] = "Buku";
			stack.value[84] = "Buku";
			stack.value[85] = "Buku";
			stack.value[86] = "Buku";
			stack.value[87] = "Buku";
			stack.value[88] = "Buku";
			stack.value[89] = "Buku";
			stack.value[90] = "Buku";
			stack.value[91] = "Buku";
			stack.value[92] = "Buku";
			stack.value[93] = "Buku";
			stack.value[94] = "Buku";
			stack.value[95] = "Buku";
			stack.value[96] = "Buku";
			stack.value[97] = "Buku";
			stack.value[98] = "Buku";
			stack.value[99] = "Buku";
			
			
			for(int i=0;i<stack.value.length;i++){System.out.println(stack.value[i]);};
}
	}
